version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      MYSQL_ROOT_PASSWORD: "users"
      MYSQL_DATABASE: "users"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network: